# Generated by Django 4.0 on 2021-12-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(max_length=80)),
                ('thread_date', models.DateTimeField(verbose_name='date published')),
                ('thread_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=500)),
                ('post_date', models.DateTimeField(verbose_name='date published')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageboard.thread')),
            ],
        ),
    ]
